name: Code check

on:
  push:
    branches:
      - master
      - develop
      - release/*
      - feature
  pull_request:
    branches:
      - master
      - develop
      - release/*
      - feature

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # - name: Build info
    #   run: |
    #     make build_info

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Tests
      run: |
        python -m pytest -v

    - name: Check coverage
      run: |
        coverage run -m pytest
        coverage report

    - name: Lint with flake8
      run: |
        flake8
